apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Chart for the nginx server
engine: gotpl
name: mod-chart
version: 3.0.6
home: http://www.nginx.org
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
keywords:
- nginx
- http
- web
- www
- reverse proxy
maintainers:
- email: ygqygq2@qq.com
  name: ygqygq2
sources:
- https://github.com/bitnami/bitnami-docker-nginx
