apiVersion: v2
appVersion: "1.0.0"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: mdb
version: 5.0.3
maintainers:
- email: ygqygq2@qq.com
  name: ygqygq2
home:
icon:
keywords:
- template
- helm
sources:
