name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ygqygq2 https://ygqygq2.github.io/charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ygqygq2
          charts_repo_url: https://ygqygq2.github.io/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Update speed up index.yaml
        run: |
          speed_up_addr="http://gh.linuxba.com/"
          release_addr="https://github.com/ygqygq2/charts/releases/"
          git checkout gh-pages
          git pull
          [ ! -d speed-up ] && mkdir speed-up
          sed "s@- ${release_addr}@- ${speed_up_addr}${release_addr}@g" index.yaml > speed-up/index.yaml
          git add -A
          is_changed=$(git status -s)
          if [ -n "$is_changed" ]; then
            git commit -sm 'Update speed-up/index.yaml' 
            git push origin gh-pages
          else
            echo "Nothing to push"
          fi
